### PR TITLE
Migrate loose json objects to folders & rename minirock to rckc

### PR DESCRIPTION
**Pull request by ZeeMaji**
Migrates all loose json objects to folders for both consistency and ease of implementing extended/custom thumbnails later.
Also renames rct1's rocket cars from "minirock" to "rckc" for consistency with it's id.

### CODE REVIEW

**Comment by spacek531** [comment]
I think there is no impetus to use the same names for RCT1 trains

**Comment by ZeeMaji** [comment]
Hm, so should i just change it to rct1.ride.minirock and change the id to that as well?

**Comment by spacek531** [comment]
oh did I leave the ID as rct1.ride.rckc? In that case its fine to rename it to that

**Comment by ZeeMaji** [comment]
It has been renamed to rct1.ride.minirock.

**Pull request merged**
